### ISSUE TITLE
U got merge conflicts

### ISSUE THREAD

**Issue by Talha-Ak** [SUmof1/chrome-calc-extension#1]
tried importing your garbage extension, doesnt work properly because u got [merge](https://github.com/SUmof1/chrome-calc-extension/blob/master/popup.js) conflicts [in](https://github.com/SUmof1/chrome-calc-extension/blob/master/popup.html) your [files](https://github.com/SUmof1/chrome-calc-extension/blob/master/manifest.json).

Go look at [SO](https://stackoverflow.com/a/10657351) and fix yo shit
plus i had to remove your extension to actually search stackoverflow lmao
![image](https://user-images.githubusercontent.com/30045102/54070641-0d162600-426b-11e9-8cdd-ad77db57db8b.png)

**Comment by SUmof1** [comment]
removed the duplicate in the html file, as for your browser breaking that isnt on my part, its just one of the side effects of loading an unpacked package as chrome warns you ;p

**Comment by Talha-Ak** [comment]
u might as well just delete this issue
